android {
    compileSdkVersion 35
    buildToolsVersion '34.0.0'

    defaultConfig {
        minSdkVersion 26
        targetSdkVersion 35
        multiDexEnabled true
        vectorDrawables.useSupportLibrary = true
    }

    android {
        ndkVersion "25.2.9519653"
    }

    packagingOptions {
        jniLibs {
            useLegacyPackaging = true
        }
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/NOTICE'
        excludes += "META-INF/native-image/**"
    }

    lintOptions {
        checkReleaseBuilds false
        abortOnError false
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
repositories {
    // jcenter()
    maven {
        url 'https://maven.google.com/'
        name 'Google'
    }
}

apply from: "libs/zoomsdk/build.gradle"

dependencies { 
    implementation fileTree(dir: 'libs/zoomsdk', include: ['*.aar', '*.gradle'])
}

